import React from 'react'
import Link from "next/link";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "About Next App",
    description: "Generated by amir",
};

function AboutLayout({
                         children,
                     }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="bg-olive-800 text-olive-500 h-full">
            <header className="p-3 flex flex-row items-center justify-between border-2 rounded-md">
                <h1>its header from about layout</h1>
                <Link href="/public" className="border-2 rounded-md p-1">go home</Link>
            </header>

            {children}
        </div>
    )
}

export default AboutLayout
